{
 "title": "Micrometer Hystrix (k8s)",
 "description": "Java metrics exposed with Micrometer",
 "tags": [
  "java",
  "micrometer",
  "k8s"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(system_cpu_count, namespace)"
   },
   {
    "name": "job",
    "label": "App",
    "query": "label_values(system_cpu_count{namespace =\"$namespace\"}, job)"
   },
   {
    "name": "pod",
    "label": "Pod Name",
    "query": "label_values(system_cpu_count{namespace =\"$namespace\", job=\"$job\"}, pod)"
   },
   {
    "name": "group",
    "label": "Group",
    "query": "label_values(hystrix_execution_total{namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}, group)"
   },
   {
    "name": "key",
    "label": "Key",
    "query": "label_values(hystrix_execution_total{namespace =\"$namespace\", job=\"$job\", pod=~\"$pod\", group=~\"$group\"}, key)"
   }
  ]
 },
 "panels": [
  { "title": "Open Circuit Breaker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Count of open circuit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hystrix_circuit_breaker_open{namespace=~\"$namespace\",job=~\"$job\",pod=~\"$pod\", group=~\"$group\", key=~\"$key\"})"
    }
   ]
  },
  {
   "title": "Open Circuit Breaker",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hystrix_circuit_breaker_open{namespace=~\"$namespace\",job=~\"$job\",pod=~\"$pod\", group=~\"$group\", key=~\"$key\"}",
     "legendFormat": "{{group}}/{{key}} - {{namespace}}/{{job}}/{{pod}}"
    }
   ]
  },
  { "title": "Hystrix Execution ( / s)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Success Event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hystrix_execution_total{namespace=~\"$namespace\",job=~\"$job\",pod=~\"$pod\", group=~\"$group\", key=~\"$key\", event=\"success\"}[1m])) by (namespace, job, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{namespace}}/{{job}}"
    }
   ]
  },
  {
   "title": "Emit Event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hystrix_execution_total{namespace=~\"$namespace\",job=~\"$job\",pod=~\"$pod\", group=~\"$group\", key=~\"$key\", event=\"emit\"}[1m])) by (namespace, job, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{namespace}}/{{job}}"
    }
   ]
  },
  {
   "title": "ShortCircuited Event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hystrix_execution_total{namespace=~\"$namespace\",job=~\"$job\",pod=~\"$pod\", group=~\"$group\", key=~\"$key\", event=\"short_circuited\"}[1m])) by (namespace, job, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{namespace}}/{{job}}"
    }
   ]
  },
  {
   "title": "BadRequest Event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hystrix_execution_total{namespace=~\"$namespace\",job=~\"$job\",pod=~\"$pod\", group=~\"$group\", key=~\"$key\", event=\"bad_request\"}[1m])) by (namespace, job, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{namespace}}/{{job}}"
    }
   ]
  },
  {
   "title": "Failure Event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hystrix_execution_total{namespace=~\"$namespace\",job=~\"$job\",pod=~\"$pod\", group=~\"$group\", key=~\"$key\", event=\"failure\"}[1m])) by (namespace, job, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{namespace}}/{{job}}"
    }
   ]
  },
  {
   "title": "Timeout Event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hystrix_execution_total{namespace=~\"$namespace\",job=~\"$job\",pod=~\"$pod\", group=~\"$group\", key=~\"$key\", event=\"timeout\"}[1m])) by (namespace, job, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{namespace}}/{{job}}"
    }
   ]
  },
  {
   "title": "SemaphoreRejected Event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hystrix_execution_total{namespace=~\"$namespace\",job=~\"$job\",pod=~\"$pod\", group=~\"$group\", key=~\"$key\", event=\"semaphore_rejected\"}[1m])) by (namespace, job, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{namespace}}/{{job}}"
    }
   ]
  },
  {
   "title": "ThreadPoolRejected Event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hystrix_execution_total{namespace=~\"$namespace\",job=~\"$job\",pod=~\"$pod\", group=~\"$group\", key=~\"$key\", event=\"thread_pool_rejected\"}[1m])) by (namespace, job, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{namespace}}/{{job}}"
    }
   ]
  },
  { "title": "Hystrix Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Latency Execution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(hystrix_latency_execution_seconds{namespace=~\"$namespace\",job=~\"$job\",pod=~\"$pod\", group=~\"$group\", key=~\"$key\"}) by (namespace, job, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{namespace}}/{{job}}"
    }
   ]
  },
  {
   "title": "Latency Execution Percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(hystrix_latency_execution_seconds_bucket{namespace=~\"$namespace\",job=~\"$job\",pod=~\"$pod\", group=~\"$group\", key=~\"$key\"}[5m])) by (namespace, job, group, key, le))",
     "legendFormat": "50p - {{group}}/{{key}} - {{namespace}}/{{job}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(hystrix_latency_execution_seconds_bucket{namespace=~\"$namespace\",job=~\"$job\",pod=~\"$pod\", group=~\"$group\", key=~\"$key\"}[5m])) by (namespace, job, group, key, le))",
     "legendFormat": "90p - {{group}}/{{key}} - {{namespace}}/{{job}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(hystrix_latency_execution_seconds_bucket{namespace=~\"$namespace\",job=~\"$job\",pod=~\"$pod\", group=~\"$group\", key=~\"$key\"}[5m])) by (namespace, job, group, key, le))",
     "legendFormat": "95p - {{group}}/{{key}} - {{namespace}}/{{job}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(hystrix_latency_execution_seconds_bucket{namespace=~\"$namespace\",job=~\"$job\",pod=~\"$pod\", group=~\"$group\", key=~\"$key\"}[5m])) by (namespace, job, group, key, le))",
     "legendFormat": "99p - {{group}}/{{key}} - {{namespace}}/{{job}}"
    }
   ]
  }
 ]
}