{
 "title": "Postgres:  Overview",
 "tags": [ "postgres" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(pg_static, instance)"
   },
   {
    "name": "db",
    "label": "DB",
    "query": "label_values(pg_stat_database_tup_fetched{instance=\"$host\", datname!~\"template.*|postgres\"}, datname)"
   }
  ]
 },
 "panels": [
  {
   "title": "PostgreSQL Version",
   "type": "singlestat",
   "description": "PostgreSQL Version being used",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "count(pg_static{instance=\"$host\"}) by(instance, short_version)",
     "legendFormat": "{{ short_version }}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "singlestat",
   "description": "Rate of transactions in this database that have been committed/rollbacked",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(irate(pg_stat_database_xact_commit{instance=\"$host\", datname=~\"$db\"}[5m])) + avg(irate(pg_stat_database_xact_rollback{instance=\"$host\", datname=~\"$db\",}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "xact_commit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of Checkpoints",
   "type": "singlestat",
   "description": "Total number of Checkpoints",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(pg_stat_bgwriter_checkpoints_req{instance=\"$host\"}) + avg(pg_stat_bgwriter_checkpoints_timed{instance=\"$host\"})"
    }
   ]
  },
  {
   "title": "Checkpoint Write Time",
   "type": "singlestat",
   "description": "Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pg_stat_bgwriter_checkpoint_write_time{instance=\"$host\"})"
    }
   ]
  },
  {
   "title": "Checkpoint Sync Time",
   "type": "singlestat",
   "description": "Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pg_stat_bgwriter_checkpoint_sync_time{instance=\"$host\"})"
    }
   ]
  },
  {
   "title": "Last Statistics Reset",
   "type": "singlestat",
   "description": "Time at which these statistics were last reset",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(pg_stat_database_stats_reset{instance=\"$host\", datname=~\"$db\"})"
    }
   ]
  },
  {
   "title": "Rows",
   "type": "graph",
   "description": "Rate of rows in this database by action performed",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "fetched",
     "expr": "avg(rate(pg_stat_database_tup_fetched{instance=\"$host\", datname=~\"$db\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "fetched",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "avg(rate(pg_stat_database_tup_returned{instance=\"$host\", datname=~\"$db\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "returned",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "avg(rate(pg_stat_database_tup_inserted{instance=\"$host\", datname=~\"$db\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "inserted",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "avg(rate(pg_stat_database_tup_updated{instance=\"$host\", datname=~\"$db\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "updated",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "avg(rate(pg_stat_database_tup_deleted{instance=\"$host\", datname=~\"$db\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "deleted",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(pg_stat_database_blks_hit{instance=\"$host\", datname=~\"$db\"}) / (avg(pg_stat_database_blks_hit{instance=\"$host\", datname=~\"$db\"}) + avg(pg_stat_database_blks_read{instance=\"$host\", datname=~\"$db\"}))"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "description": "Number of backends currently connected to this database",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(pg_stat_database_numbackends{instance=\"$host\", datname=~\"$db\"})"
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Buffers Allocated",
     "expr": "avg(rate(pg_stat_bgwriter_buffers_alloc{instance=\"$host\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "alloc",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "avg(rate(pg_stat_bgwriter_buffers_backend_fsync{instance=\"$host\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "backend_fsync",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "avg(rate(pg_stat_bgwriter_buffers_backend{instance=\"$host\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "avg(rate(pg_stat_bgwriter_buffers_clean{instance=\"$host\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "clean",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "avg(rate(pg_stat_bgwriter_buffers_checkpoint{instance=\"$host\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "checkpoint",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Activity",
   "type": "graph",
   "description": "Number of connections in this state",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(pg_stat_activity_count{instance=\"$host\",datname=~\"$db\"}[5m])) by(state)",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Active Transactions Max Duration",
   "type": "graph",
   "description": "Max duration in seconds any active transaction has been running",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(pg_stat_activity_max_tx_duration{instance=\"$host\",datname=~\"$db\"}) by(instance, state)",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "graph",
   "description": "Number of locks",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(pg_locks_count{instance=\"$host\",datname=~\"$db\"}[5m])) by(mode)",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "description": "Number of conflicts and deadlocks detected in this database",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "conflicts",
     "expr": "avg(rate(pg_stat_database_deadlocks{instance=\"$host\", datname=~\"$db\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "deadlocks",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "deadlocks",
     "expr": "avg(rate(pg_stat_database_conflicts{instance=\"$host\", datname=~\"$db\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "conflicts",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "deadlocks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Read/Write Time",
   "type": "graph",
   "description": "Time spent reading and writing data file blocks by backends in this database",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(pg_stat_database_blk_read_time{instance=\"$host\", datname=~\"$db\"})",
     "legendFormat": "read"
    },
    {
     "expr": "avg(pg_stat_database_blk_write_time{instance=\"$host\", datname=~\"$db\"})",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Data Written to Temp files",
   "type": "graph",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(pg_stat_database_temp_bytes{instance=\"$host\", datname=~\"$db\"})"
    }
   ]
  }
 ]
}