{
 "title": "PKS Deployment",
 "tags": [
  "k8s",
  "pks"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(pks_kube_node_info_gauge, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(pks_kube_deployment_created_gauge{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "deployment",
    "query": "label_values(pks_kube_deployment_created_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\"}, deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Deployments by Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(pks_kube_deployment_created_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", deployment=~\"$deployment\"}) by (cluster, namespace, deployment)",
     "legendFormat": "{{deployment}}/{{namespace}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Replicas per Deployment",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pks_kube_deployment_status_replicas_available_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "available - {{deployment}}/{{namespace}}/{{cluster}}"
    },
    {
     "expr": "pks_kube_deployment_status_replicas_unavailable_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "unavailable - {{deployment}}/{{namespace}}/{{cluster}}"
    },
    {
     "expr": "pks_kube_deployment_status_replicas_updated_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "updated - {{deployment}}/{{namespace}}/{{cluster}}"
    }
   ]
  }
 ]
}
{
 "title": "PKS Namespace",
 "tags": [
  "k8s",
  "pks"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(pks_kube_node_info_gauge, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(pks_kube_pod_info_gauge{cluster=~\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Count By Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(pks_heapster_pod_uptime{cluster=~\"$cluster\", namespace_name=~\"$namespace\"}) by (cluster, namespace_name)",
     "legendFormat": "{{namespace_name}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Pod Container Count By Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(pks_heapster_pod_container_uptime{cluster=~\"$cluster\",namespace_name=~\"$namespace\"}) by (cluster, namespace_name)",
     "legendFormat": "{{namespace_name}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_ns_memory_usage{cluster=~\"$cluster\", namespace_name=~\"$namespace\"}",
     "legendFormat": "{{namespace_name}} - {{cluster}}"
    }
   ]
  }
 ]
}
{
 "title": "PKS Node",
 "tags": [
  "k8s",
  "pks"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(pks_kube_node_info_gauge, cluster)"
   },
   {
    "name": "node",
    "query": "label_values(pks_kube_node_info_gauge{cluster=~\"$cluster\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_node_cpu_node_utilization{cluster=~\"$cluster\",nodename=~\"$node\"}",
     "legendFormat": "{{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "CPU Usage Rate by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_node_cpu_usage_rate{cluster=~\"$cluster\",nodename=~\"$node\"}",
     "legendFormat": "{{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory Utilization by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_node_memory_working_set{cluster=~\"$cluster\",nodename=~\"$node\"} / pks_heapster_node_memory_node_capacity{cluster=~\"$cluster\",nodename=~\"$node\"}",
     "legendFormat": "{{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_node_memory_usage{cluster=~\"$cluster\",nodename=~\"$node\"} / pks_heapster_node_memory_node_capacity{cluster=~\"$cluster\",nodename=~\"$node\"}",
     "legendFormat": "{{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "CPU Allocatable vs Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "pks_kube_node_status_allocatable_cpu_cores_gauge{cluster=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "allocatable_core - {{cluster}}/{{node}}"
    },
    {
     "expr": "pks_kube_node_status_capacity_cpu_cores_gauge{cluster=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "capacity_core - {{cluster}}/{{node}}"
    }
   ]
  },
  {
   "title": "Pod Resources Allocatable vs Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pks_kube_node_status_allocatable_pods_gauge{cluster=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "allocatable_pod_res - {{cluster}}/{{node}}"
    },
    {
     "expr": "pks_kube_node_status_capacity_pods_gauge{cluster=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "capacity_pod_res - {{cluster}}/{{node}}"
    }
   ]
  },
  {
   "title": "Memory Allocatable vs Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "pks_kube_node_status_allocatable_memory_bytes_gauge{cluster=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "allocatable_mem - {{cluster}}/{{node}}"
    },
    {
     "expr": "pks_kube_node_status_capacity_memory_bytes_gauge{cluster=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "capacity_mem - {{cluster}}/{{node}}"
    }
   ]
  },
  {
   "title": "Bytes Received Rate By Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 15 },
   "yaxes": [
    { "format": "bytes", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "rate(pks_heapster_node_network_rx{cluster=~\"$cluster\",nodename=~\"$node\"}[10m])",
     "legendFormat": "{{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "Bytes Transferred Rate By Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 15 },
   "yaxes": [
    { "format": "bytes", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "rate(pks_heapster_node_network_tx{cluster=~\"$cluster\",nodename=~\"$node\"}[10m])",
     "legendFormat": "{{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "Networking Errors By Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "rate(pks_heapster_node_network_rx_errors{cluster=~\"$cluster\",nodename=~\"$node\"}[10m])",
     "legendFormat": "rx_err - {{cluster}}/{{nodename}}"
    },
    {
     "expr": "rate(pks_heapster_node_network_tx_errors{cluster=~\"$cluster\",nodename=~\"$node\"}[10m])",
     "legendFormat": "tx_err - {{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "File System Usage By Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 23 },
   "yaxes": [
    { "format": "bytes", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_node_filesystem_usage{cluster=~\"$cluster\",nodename=~\"$node\"}",
     "legendFormat": " {{resource_id}} - {{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "File System - Available Storage by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 23 },
   "yaxes": [
    { "format": "bytes", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_node_filesystem_limit{cluster=~\"$cluster\",nodename=~\"$node\"} - pks_heapster_node_filesystem_usage{cluster=~\"$cluster\",nodename=~\"$node\"}",
     "legendFormat": " {{resource_id}} - {{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "File System - Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_node_filesystem_usage{cluster=~\"$cluster\",nodename=~\"$node\"} / pks_heapster_node_filesystem_limit{cluster=~\"$cluster\",nodename=~\"$node\"}",
     "legendFormat": " {{resource_id}} - {{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk IO Read Rate by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 31 },
   "yaxes": [
    { "format": "Bps", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pks_heapster_node_disk_io_read_bytes{cluster=~\"$cluster\",nodename=~\"$node\"}[10m])) by (cluster, nodename)",
     "legendFormat": "{{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk IO Write Rate by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pks_heapster_node_disk_io_write_bytes{cluster=~\"$cluster\",nodename=~\"$node\"}[10m])) by (cluster, nodename)",
     "legendFormat": "{{cluster}}/{{nodename}}"
    }
   ]
  }
 ]
}
{
 "title": "PKS Overview",
 "tags": [
  "k8s",
  "pks"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(pks_kube_node_info_gauge, cluster)"
   },
   {
    "name": "node",
    "query": "label_values(pks_kube_node_info_gauge{cluster=~\"$cluster\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(pks_kube_node_info_gauge{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Namespaces Active",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pks_kube_namespace_status_phase_gauge{cluster=~\"$cluster\", phase=\"Active\"})"
    }
   ]
  },
  {
   "title": "Namespaces Terminating",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pks_kube_namespace_status_phase_gauge{cluster=~\"$cluster\", phase=\"Terminating\"})"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pks_kube_pod_status_phase_gauge{cluster=~\"$cluster\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pks_kube_pod_status_phase_gauge{cluster=~\"$cluster\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pks_kube_pod_status_phase_gauge{cluster=~\"$cluster\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Containers Running",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pks_kube_pod_container_status_running_gauge{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pks_kube_pod_container_status_terminated_gauge{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(pks_kube_pod_container_status_waiting_gauge{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Restarts of Containers",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pks_kube_pod_container_status_restarts_total_counter{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(pks_kube_deployment_created_gauge{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(pks_kube_service_created_gauge{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pks_heapster_cluster_memory_usage{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Max Node Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pks_heapster_node_memory_working_set{cluster=~\"$cluster\", nodename=~\"$node\"} / pks_heapster_node_memory_node_capacity{cluster=~\"$cluster\", nodename=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Max Node CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pks_heapster_node_cpu_node_utilization{cluster=~\"$cluster\", nodename=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Max Node Storage Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pks_heapster_node_filesystem_usage{cluster=~\"$cluster\", nodename=~\"$node\"} / pks_heapster_node_filesystem_limit{cluster=~\"$cluster\", nodename=~\"$node\"})"
    }
   ]
  }
 ]
}
{
 "title": "PKS Pod Container",
 "tags": [
  "k8s",
  "pks"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(pks_kube_node_info_gauge, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(pks_kube_pod_info_gauge{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(pks_kube_pod_info_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "query": "label_values(pks_kube_pod_container_info_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage Rate By Pod Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_pod_container_cpu_usage_rate{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"}",
     "legendFormat": "{{container_name}}/{{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_pod_container_memory_usage{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"}",
     "legendFormat": "{{container_name}}/{{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Disk IO Read Rate by Pod Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(pks_heapster_pod_container_disk_io_read_bytes{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"}[5m])",
     "legendFormat": "{{container_name}}/{{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Disk IO Write Rate by Pod Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(pks_heapster_pod_container_disk_io_write_bytes{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"}[5m])",
     "legendFormat": "{{container_name}}/{{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Pod Containers Running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pks_kube_pod_container_status_running_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by (cluster, namespace, pod, container)",
     "legendFormat": "{{container}}/{{pod}}/{{namespace}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Pod Containers Terminated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pks_kube_pod_container_status_terminated_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by (cluster, namespace, pod, container)",
     "legendFormat": "{{container}}/{{pod}}/{{namespace}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Pod Containers Terminated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pks_kube_pod_container_status_terminated_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by (cluster, namespace, pod, container)",
     "legendFormat": "{{container}}/{{pod}}/{{namespace}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Restarts per Pod Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pks_kube_pod_container_status_restarts_total_counter{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "{{container}}/{{pod}}/{{namespace}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Page Faults Rate By Pod Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "page faults / sec" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_pod_container_memory_page_faults_rate{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"}",
     "legendFormat": "{{container_name}}/{{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "File System Usage By Pod Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_pod_container_filesystem_usage{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"}",
     "legendFormat": "{{resource_id}} - {{container_name}}/{{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  }
 ]
}
{
 "title": "PKS Pod",
 "tags": [
  "k8s",
  "pks"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(pks_kube_node_info_gauge, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(pks_kube_pod_info_gauge{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(pks_kube_pod_info_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage Rate By Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_pod_cpu_usage_rate{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "{{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_pod_memory_usage{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "{{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Pods Available in Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pks_kube_pod_status_ready_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", condition=\"true\"}) by (cluster, namespace)",
     "legendFormat": "{{namespace}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Pods Unavailable in Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pks_kube_pod_status_ready_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", condition=\"false\"}) by (cluster, namespace)",
     "legendFormat": "{{namespace}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pks_kube_pod_status_phase_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", phase=\"Running\"}) by (cluster, namespace, pod)",
     "legendFormat": "{{pod}}/{{namespace}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pks_kube_pod_status_phase_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", phase=\"Failed\"}) by (cluster, namespace, pod)",
     "legendFormat": "{{pod}}/{{namespace}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pks_kube_pod_status_phase_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", phase=\"Pending\"}) by (cluster, namespace, pod)",
     "legendFormat": "{{pod}}/{{namespace}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pks_kube_pod_status_phase_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", phase=\"Succeeded\"}) by (cluster, namespace, pod)",
     "legendFormat": "{{pod}}/{{namespace}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Page Faults Rate By Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "page faults / sec" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_pod_memory_page_faults_rate{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "{{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Bytes Received Rate By Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(pks_heapster_pod_network_rx{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Bytes Transferred Rate By Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(pks_heapster_pod_network_tx{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Networking Errors By Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(pks_heapster_pod_network_rx_errors{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\"}[5m])",
     "legendFormat": "rx_err - {{pod_name}}/{{namespace_name}}/{{cluster}}"
    },
    {
     "expr": "rate(pks_heapster_pod_network_tx_errors{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\"}[5m])",
     "legendFormat": "tx_err - {{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  }
 ]
}