{
 "title": "Concourse: Overview",
 "tags": [ "concourse" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(concourse_workers_containers, bosh_deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Builds Started",
   "type": "singlestat",
   "description": "Total number of Concourse builds started",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(concourse_builds_started_total{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment)"
    }
   ]
  },
  {
   "title": "Builds Finished",
   "type": "singlestat",
   "description": "Total number of Concourse builds finished",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(concourse_builds_finished_total{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment)"
    }
   ]
  },
  {
   "title": "Builds Succeeded",
   "type": "singlestat",
   "description": "Total number of Concourse builds succeeded",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(concourse_builds_succeeded_total{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment)"
    }
   ]
  },
  {
   "title": "Builds Aborted",
   "type": "singlestat",
   "description": "Total number of Concourse builds aborted",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(concourse_builds_aborted_total{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment)"
    }
   ]
  },
  {
   "title": "Builds Errored",
   "type": "singlestat",
   "description": "Total number of Concourse builds errored",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(concourse_builds_errored_total{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment)"
    }
   ]
  },
  {
   "title": "Builds Failed",
   "type": "singlestat",
   "description": "Total number of Concourse builds failed",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(concourse_builds_failed_total{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment)"
    }
   ]
  },
  {
   "title": "Builds Started / Finished",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(concourse_builds_started_total{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment)",
     "legendFormat": "Started"
    },
    {
     "expr": "max(concourse_builds_finished_total{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment)",
     "legendFormat": "Finished"
    }
   ]
  },
  {
   "title": "HTTP Response Duration",
   "type": "graph",
   "description": "HTTP response duration",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(concourse_http_responses_duration_seconds_sum{bosh_deployment=~\"$bosh_deployment\"}[5m]) / rate(concourse_http_responses_duration_seconds_count{bosh_deployment=~\"$bosh_deployment\"}[5m])) by(bosh_deployment, route)",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "Worker Containers",
   "type": "graph",
   "description": "Number of containers per worker",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(concourse_workers_containers{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, worker)",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Worker Volumes",
   "type": "graph",
   "description": "Number of volumes per worker",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(concourse_workers_volumes{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, worker)",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "graph",
   "description": "Current number of concourse database connections",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(concourse_db_connections{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment, dbname)",
     "legendFormat": "{{ dbname }}"
    }
   ]
  },
  {
   "title": "Database Queries",
   "type": "graph",
   "description": "Recent number of Concourse database queries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(concourse_db_queries{bosh_deployment=~\"$bosh_deployment\"}) by(bosh_deployment)",
     "legendFormat": "Queries"
    }
   ]
  }
 ]
}
{
 "title": "Concourse: Pipelines",
 "tags": [ "concourse" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(concourse_builds_finished, bosh_deployment)"
   },
   {
    "name": "pipeline",
    "label": "Pipeline",
    "query": "label_values(concourse_builds_finished{bosh_deployment=~\"$bosh_deployment\"}, pipeline)"
   }
  ]
 },
 "panels": [
  {
   "title": "Scheduling: Full",
   "type": "graph",
   "description": "Last time taken to schedule an entire pipeline",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(concourse_scheduling_full_duration_seconds{bosh_deployment=~\"$bosh_deployment\", pipeline=~\"$pipeline\"}) by(bosh_deployment, pipeline)",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Scheduling: Loading",
   "type": "graph",
   "description": "Last time taken to load version information from the database for a pipeline",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(concourse_scheduling_loading_duration_seconds{bosh_deployment=~\"$bosh_deployment\", pipeline=~\"$pipeline\"}) by(bosh_deployment, pipeline)",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Scheduling: Job",
   "type": "graph",
   "description": "Last time taken to calculate the set of valid input versions for a pipeline",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(concourse_scheduling_job_duration_seconds{bosh_deployment=~\"$bosh_deployment\", pipeline=~\"$pipeline\"}) by(bosh_deployment, pipeline)",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Builds Finished",
   "type": "graph",
   "description": "Count of builds finished",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(concourse_builds_finished{bosh_deployment=~\"$bosh_deployment\", pipeline=~\"$pipeline\"}) by(bosh_deployment, pipeline, status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Build Duration",
   "type": "graph",
   "description": "Build time",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(concourse_builds_duration_seconds_sum{bosh_deployment=~\"$bosh_deployment\", pipeline=~\"$pipeline\"}[5m]) / rate(concourse_builds_duration_seconds_count{bosh_deployment=~\"$bosh_deployment\", pipeline=~\"$pipeline\"}[5m])) by(bosh_deployment, pipeline)",
     "legendFormat": "Duration"
    }
   ]
  }
 ]
}