{
 "title": "BOSH: Jobs",
 "tags": [ "bosh" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(bosh_job_healthy, environment)"
   },
   {
    "name": "bosh_director",
    "label": "Director",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\"}, bosh_name)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment!=\"bosh-health-check\"}, bosh_deployment)"
   },
   {
    "name": "bosh_job_name",
    "label": "Job",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name!~\"^compilation.*\"}, bosh_job_name)"
   },
   {
    "name": "bosh_job_index",
    "label": "Index",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}, bosh_job_index)"
   }
  ]
 },
 "panels": [
  {
   "title": "Jobs Health",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(bosh_job_mem_percent{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"}) by(bosh_deployment,bosh_job_name,bosh_job_index)",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_index }}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(bosh_job_swap_percent{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"}) by(bosh_deployment,bosh_job_name,bosh_job_index)",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_index }}"
    }
   ]
  },
  {
   "title": "CPU (sys) Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(bosh_job_cpu_sys{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"}) by(bosh_deployment,bosh_job_name,bosh_job_index)",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_index }}"
    }
   ]
  },
  {
   "title": "CPU (user) Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(bosh_job_cpu_user{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"}) by(bosh_deployment,bosh_job_name,bosh_job_index)",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_index }}"
    }
   ]
  },
  {
   "title": "CPU (wait) Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(bosh_job_cpu_wait{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"}) by(bosh_deployment,bosh_job_name,bosh_job_index)",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_index }}"
    }
   ]
  },
  {
   "title": "Load (avg01)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(bosh_job_load_avg01{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"}) by(bosh_deployment,bosh_job_name,bosh_job_index)",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_index }}"
    }
   ]
  },
  {
   "title": "Load (avg05)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(bosh_job_load_avg05{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"}) by(bosh_deployment,bosh_job_name,bosh_job_index)",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_index }}"
    }
   ]
  },
  {
   "title": "Load (avg15)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(bosh_job_load_avg15{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"}) by(bosh_deployment,bosh_job_name,bosh_job_index)",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_index }}"
    }
   ]
  },
  {
   "title": "System Disk Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(bosh_job_system_disk_percent{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"}) by(bosh_deployment,bosh_job_name,bosh_job_index)",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_index }}"
    }
   ]
  },
  {
   "title": "Ephemeral Disk Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(bosh_job_ephemeral_disk_percent{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"}) by(bosh_deployment,bosh_job_name,bosh_job_index)",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_index }}"
    }
   ]
  },
  {
   "title": "Persistent Disk Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(bosh_job_persistent_disk_percent{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"}) by(bosh_deployment,bosh_job_name,bosh_job_index)",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_index }}"
    }
   ]
  }
 ]
}
{
 "title": "BOSH: Overview",
 "description": "BOSH Overview",
 "tags": [ "bosh" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(bosh_job_healthy, environment)"
   },
   {
    "name": "bosh_director",
    "label": "Director",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\"}, bosh_name)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment!=\"bosh-health-check\"}, bosh_deployment)"
   },
   {
    "name": "bosh_job_name",
    "label": "Job",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name!~\"^compilation.*\"}, bosh_job_name)"
   },
   {
    "name": "bosh_job_index",
    "label": "Index",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}, bosh_job_index)"
   }
  ]
 },
 "panels": [
  {
   "title": "Jobs Health",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Processes Health",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(bosh_job_process_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Avg Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_job_mem_percent{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Avg Swap Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_job_swap_percent{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Avg CPU (sys)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_job_cpu_sys{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Avg CPU (user)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_job_cpu_user{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Avg CPU (wait)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_job_cpu_wait{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Avg Load (avg01)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_job_load_avg01{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Avg Load (avg05)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_job_load_avg05{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Avg Load (avg15)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_job_load_avg15{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Avg System Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_job_system_disk_percent{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Avg Ephemeral Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_job_ephemeral_disk_percent{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Avg Persistent Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_job_persistent_disk_percent{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  }
 ]
}
{
 "title": "BOSH: Processes",
 "tags": [ "bosh" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(bosh_job_process_healthy, environment)"
   },
   {
    "name": "bosh_director",
    "label": "Director",
    "query": "label_values(bosh_job_process_healthy{environment=~\"$environment\"}, bosh_name)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(bosh_job_process_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment!=\"bosh-health-check\"}, bosh_deployment)"
   },
   {
    "name": "bosh_job_name",
    "label": "Job",
    "query": "label_values(bosh_job_process_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\"}, bosh_job_name)"
   },
   {
    "name": "bosh_job_index",
    "label": "Index",
    "query": "label_values(bosh_job_process_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}, bosh_job_index)"
   },
   {
    "name": "bosh_job_process_name",
    "label": "Process",
    "query": "label_values(bosh_job_process_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"}, bosh_job_process_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Processes Health",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(bosh_job_process_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\",bosh_job_process_name=~\"$bosh_job_process_name\"})"
    }
   ]
  },
  {
   "title": "Failing Processes",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(bosh_job_process_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\",bosh_job_process_name=~\"$bosh_job_process_name\"}) by(bosh_deployment, bosh_job_name, bosh_job_index, bosh_job_process_name) < 1",
     "legendFormat": "{{ bosh_deployment }}/{{ bosh_job_name }}/{{ bosh_job_index }}: {{ bosh_job_process_name }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(bosh_job_process_cpu_total{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\",bosh_job_process_name=~\"$bosh_job_process_name\"}) by(bosh_deployment, bosh_job_name,  bosh_job_index, bosh_job_process_name)",
     "legendFormat": "{{bosh_deployment}}/{{bosh_job_name}}/{{bosh_job_index}}/{{bosh_job_process_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(bosh_job_process_mem_percent{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\",bosh_job_process_name=~\"$bosh_job_process_name\"}) by(bosh_deployment, bosh_job_name, bosh_job_index, bosh_job_process_name)",
     "legendFormat": "{{bosh_deployment}}/{{bosh_job_name}}/{{bosh_job_index}}/{{bosh_job_process_name}}"
    }
   ]
  }
 ]
}
{
 "title": "BOSH: System Disk Performance",
 "tags": [ "bosh" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(bosh_job_healthy, environment)"
   },
   {
    "name": "bosh_director",
    "label": "Director",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\"}, bosh_name)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\"}, bosh_deployment)"
   },
   {
    "name": "bosh_job_name",
    "label": "Job",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\"}, bosh_job_name)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}, bosh_job_ip)"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "label_values(node_disk_reads_completed_total{instance=~\"$host(:[0-9]+)?\", device!~\"dm-.+\"}, device)"
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Latency",
   "type": "graph",
   "description": "Shows average latency for Reads and Writes IO Devices. Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems. Higher than normal latency also can indicate internal storage problems.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(rate(node_disk_read_time_seconds_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval]) / rate(node_disk_reads_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval])) or (irate(node_disk_read_time_seconds_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m]) / irate(node_disk_reads_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m]))",
     "legendFormat": "Read: {{ device }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "(rate(node_disk_write_time_seconds_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval]) / rate(node_disk_writes_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval])) or (irate(node_disk_write_time_seconds_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m]) / irate(node_disk_writes_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m]))",
     "legendFormat": "Write: {{ device }}"
    }
   ]
  },
  {
   "title": "Disk Operations",
   "type": "graph",
   "description": "Shows amount of physical IOs (reads and writes) different devices are serving. Spikes in number of IOs served often corresponds to performance problems due to IO subsystem overload.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_reads_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval]) or irate(node_disk_reads_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m])",
     "legendFormat": "Read: {{ device }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_writes_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval]) or irate(node_disk_writes_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m])",
     "legendFormat": "Write: {{ device }}"
    }
   ]
  },
  {
   "title": "Disk Bandwidth",
   "type": "graph",
   "description": "Shows volume of reads and writes the storage is handling. This can be better measure of IO capacity usage for network attached and SSD storage as it is often bandwidth limited. Amount of data being written to the disk can be used to estimate Flash storage life time.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_read_bytes_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval]) or irate(node_disk_read_bytes_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m])",
     "legendFormat": "Read: {{ device }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_written_bytes_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval]) or irate(node_disk_written_bytes_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m])",
     "legendFormat": "Write: {{ device }}"
    }
   ]
  },
  {
   "title": "Disk Load",
   "type": "graph",
   "description": "Disk Load shows how much disk was loaded for reads or writes as average number of outstanding requests at different period of time. High disk load is a good measure of actual storage utilization. Different storage types handle load differently - some will show latency increases on low loads others can handle higher load with no problems.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_read_time_seconds_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval])/1000 or irate(node_disk_read_time_seconds_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m])/1000",
     "legendFormat": "Read: {{ device }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_write_time_seconds_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval])/1000 or irate(node_disk_write_time_seconds_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m])/1000",
     "legendFormat": "Write: {{ device }}"
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "graph",
   "description": "Shows disk Utilization as percent of the time when there was at least one IO request in flight. It is designed to match utilization available in iostat tool. It is not very good measure of true IO Capacity Utilization. Consider looking at IO latency and Disk Load Graphs instead.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_io_time_seconds_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval])/1000 or irate(node_disk_io_time_seconds_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m])/1000",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Disk Operations Merge Ratio",
   "type": "graph",
   "description": "Shows how effectively Operating System is able to merge logical IO requests into physical requests. This is a good measure of the IO locality which can be used for workload characterization.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(1 + rate(node_disk_reads_merged_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval]) / rate(node_disk_reads_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval])) or (1 + irate(node_disk_reads_merged_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m]) / irate(node_disk_reads_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m]))",
     "legendFormat": "Read Ratio: {{ device }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "(1 + rate(node_disk_writes_merged_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval]) / rate(node_disk_writes_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval])) or (1 + irate(node_disk_writes_merged_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m]) / irate(node_disk_writes_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m]))",
     "legendFormat": "Write Ratio: {{ device }}"
    }
   ]
  },
  {
   "title": "Disk IO Size",
   "type": "graph",
   "description": "Shows average size of a single disk operation.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$host(:[0-9]+)?\", device=~\"$device\"}[$interval]) / 512 / rate(node_disk_reads_completed_total{instance=~\"$host(:[0-9]+)?\", device=~\"$device\"}[$interval]) or irate(node_disk_read_bytes_total{instance=~\"$host(:[0-9]+)?\", device=~\"$device\"}[5m]) / 512 / irate(node_disk_reads_completed_total{instance=~\"$host(:[0-9]+)?\", device=~\"$device\"}[5m]) ",
     "legendFormat": "Read size: {{ device }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$host(:[0-9]+)?\", device=~\"$device\"}[$interval]) / 512 / rate(node_disk_writes_completed_total{instance=~\"$host(:[0-9]+)?\", device=~\"$device\"}[$interval]) or irate(node_disk_written_bytes_total{instance=~\"$host(:[0-9]+)?\", device=~\"$device\"}[5m]) / 512 / irate(node_disk_writes_completed_total{instance=~\"$host(:[0-9]+)?\", device=~\"$device\"}[5m]) ",
     "legendFormat": "Write size: {{ device }}"
    }
   ]
  }
 ]
}
{
 "title": "BOSH: System Disk Space",
 "tags": [ "bosh" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(bosh_job_healthy, environment)"
   },
   {
    "name": "bosh_director",
    "label": "Director",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\"}, bosh_name)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\"}, bosh_deployment)"
   },
   {
    "name": "bosh_job_name",
    "label": "Job",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\"}, bosh_job_name)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}, bosh_job_ip)"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "label_values(node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}, mountpoint)"
   }
  ]
 },
 "panels": [
  {
   "title": "Mountpoint $mountpoint",
   "type": "graph",
   "description": "Amount of disk space used and available on various mount points.  Running out of disk space on OS volume,  database volume or volume used for temporary space can cause downtime.   Some storage may also have reduced performance when small amount of space is available.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "repeat": "mountpoint",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_size_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"} - node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Used (device {{ device }}, {{ fstype }})"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\",  fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Free (device {{ device }}, {{ fstype }})"
    }
   ]
  },
  {
   "title": "Mountpoint $mountpoint",
   "type": "graph",
   "description": "Amount of disk space used and available on various mount points.  Running out of disk space on OS volume,  database volume or volume used for temporary space can cause downtime.   Some storage may also have reduced performance when small amount of space is available.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_size_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"} - node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Used (device {{ device }}, {{ fstype }})"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\",  fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Free (device {{ device }}, {{ fstype }})"
    }
   ]
  },
  {
   "title": "Mountpoint $mountpoint",
   "type": "graph",
   "description": "Amount of disk space used and available on various mount points.  Running out of disk space on OS volume,  database volume or volume used for temporary space can cause downtime.   Some storage may also have reduced performance when small amount of space is available.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_size_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"} - node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Used (device {{ device }}, {{ fstype }})"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\",  fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Free (device {{ device }}, {{ fstype }})"
    }
   ]
  },
  {
   "title": "Mountpoint $mountpoint",
   "type": "graph",
   "description": "Amount of disk space used and available on various mount points.  Running out of disk space on OS volume,  database volume or volume used for temporary space can cause downtime.   Some storage may also have reduced performance when small amount of space is available.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_size_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"} - node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Used (device {{ device }}, {{ fstype }})"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\",  fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Free (device {{ device }}, {{ fstype }})"
    }
   ]
  },
  {
   "title": "Mountpoint $mountpoint",
   "type": "graph",
   "description": "Amount of disk space used and available on various mount points.  Running out of disk space on OS volume,  database volume or volume used for temporary space can cause downtime.   Some storage may also have reduced performance when small amount of space is available.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_size_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"} - node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Used (device {{ device }}, {{ fstype }})"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\",  fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Free (device {{ device }}, {{ fstype }})"
    }
   ]
  },
  {
   "title": "Mountpoint $mountpoint",
   "type": "graph",
   "description": "Amount of disk space used and available on various mount points.  Running out of disk space on OS volume,  database volume or volume used for temporary space can cause downtime.   Some storage may also have reduced performance when small amount of space is available.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_size_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"} - node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Used (device {{ device }}, {{ fstype }})"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\",  fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Free (device {{ device }}, {{ fstype }})"
    }
   ]
  },
  {
   "title": "Mountpoint $mountpoint",
   "type": "graph",
   "description": "Amount of disk space used and available on various mount points.  Running out of disk space on OS volume,  database volume or volume used for temporary space can cause downtime.   Some storage may also have reduced performance when small amount of space is available.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_size_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"} - node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Used (device {{ device }}, {{ fstype }})"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\",  fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Free (device {{ device }}, {{ fstype }})"
    }
   ]
  }
 ]
}
{
 "title": "BOSH: System Overview",
 "tags": [ "bosh" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(bosh_job_healthy, environment)"
   },
   {
    "name": "bosh_director",
    "label": "Director",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\"}, bosh_name)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\"}, bosh_deployment)"
   },
   {
    "name": "bosh_job_name",
    "label": "Job",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\"}, bosh_job_name)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}, bosh_job_ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "node_time_seconds{instance=~\"$host(:[0-9]+)?\"} - node_boot_time_seconds{instance=~\"$host(:[0-9]+)?\"}"
    }
   ]
  },
  {
   "title": "Virtual CPUs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"user\", instance=~\"$host(:[0-9]+)?\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host(:[0-9]+)?\"}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(node_memory_MemAvailable_bytes{instance=~\"$host(:[0-9]+)?\"} or (node_memory_MemFree_bytes{instance=~\"$host(:[0-9]+)?\"} + node_memory_Buffers_bytes{instance=~\"$host(:[0-9]+)?\"} + node_memory_Cached_bytes{instance=~\"$host(:[0-9]+)?\"})) / node_memory_MemTotal_bytes{instance=~\"$host(:[0-9]+)?\"} * 100"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "node_load1{instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Load 1m"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "ode_memory_MemTotal_bytes{instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Total"
    },
    {
     "calculatedInterval": "2s",
     "expr": "ode_memory_MemTotal_bytes{instance=~\"$host(:[0-9]+)?\"} - (node_memory_MemAvailable_bytes{instance=~\"$host(:[0-9]+)?\"} or (node_memory_MemFree_bytes{instance=~\"$host(:[0-9]+)?\"} + node_memory_Buffers_bytes{instance=~\"$host(:[0-9]+)?\"} + node_memory_Cached_bytes{instance=~\"$host(:[0-9]+)?\"}))",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$host(:[0-9]+)?\"} or (node_memory_MemFree_bytes{instance=~\"$host(:[0-9]+)?\"} + node_memory_Buffers_bytes{instance=~\"$host(:[0-9]+)?\"} + node_memory_Cached_bytes{instance=~\"$host(:[0-9]+)?\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"$host(:[0-9]+)?\"}[$interval])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\", instance=~\"$host(:[0-9]+)?\"})) or sum(irate(node_cpu_seconds_total{instance=~\"$host(:[0-9]+)?\"}[5m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\", instance=~\"$host(:[0-9]+)?\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory Distribution",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host(:[0-9]+)?\"} - (node_memory_MemFree_bytes{instance=~\"$host(:[0-9]+)?\"} + node_memory_Buffers_bytes{instance=~\"$host(:[0-9]+)?\"} + node_memory_Cached_bytes{instance=~\"$host(:[0-9]+)?\"})",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemFree_bytes{instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Free"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Buffers_bytes{instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Buffers"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Cached_bytes{instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_forks_total{instance=~\"$host(:[0-9]+)?\"}[$interval]) or irate(node_forks_total{instance=~\"$host(:[0-9]+)?\"}[5m])",
     "legendFormat": "Forks"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_running{instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Processes in runnable state"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_blocked{instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Processes blocked waiting for I/O to complete"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_context_switches_total{instance=~\"$host(:[0-9]+)?\"}[$interval]) or irate(node_context_switches_total{instance=~\"$host(:[0-9]+)?\"}[5m])",
     "legendFormat": "Context Switches"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_intr_total{instance=~\"$host(:[0-9]+)?\"}[$interval]) or irate(node_intr_total{instance=~\"$host(:[0-9]+)?\"}[5m])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$host(:[0-9]+)?\", device!=\"lo\"}[$interval]) or irate(node_network_receive_bytes_total{instance=~\"$host(:[0-9]+)?\", device!=\"lo\"}[5m])",
     "legendFormat": "Inbound: {{ device }}"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$host(:[0-9]+)?\", device!=\"lo\"}[$interval]) or irate(node_network_transmit_bytes_total{instance=~\"$host(:[0-9]+)?\", device!=\"lo\"}[5m])",
     "legendFormat": "Outbound: {{ device }}"
    }
   ]
  },
  {
   "title": "Network Utilization Hourly",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$host(:[0-9]+)?\", device!=\"lo\"}[1h]))",
     "legendFormat": "Received"
    },
    {
     "calculatedInterval": "2s",
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$host(:[0-9]+)?\", device!=\"lo\"}[1h]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$host(:[0-9]+)?\"} - node_memory_SwapFree_bytes{instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_SwapFree_bytes{instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pswpin{instance=~\"$host(:[0-9]+)?\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{instance=~\"$host(:[0-9]+)?\"}[5m]) * 4096",
     "legendFormat": "Swap In"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pswpout{instance=~\"$host(:[0-9]+)?\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{instance=~\"$host(:[0-9]+)?\"}[5m]) * 4096",
     "legendFormat": "Swap Out"
    }
   ]
  },
  {
   "title": "I/O Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgin{instance=~\"$host(:[0-9]+)?\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=~\"$host(:[0-9]+)?\"}[5m]) * 1024",
     "legendFormat": "Page In"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgout{instance=~\"$host(:[0-9]+)?\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=~\"$host(:[0-9]+)?\"}[5m]) * 1024",
     "legendFormat": "Page Out"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_filefd_maximum{instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Limit"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_filefd_allocated{instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Allocated"
    }
   ]
  }
 ]
}