{
 "title": "Spring Cloud Gateway",
 "tags": [
  "java",
  "micrometer"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "gatewayService",
    "label": "Gateway Service",
    "query": "label_values(gateway_requests_seconds_count,job)"
   },
   {
    "name": "routeId",
    "label": "Route Id",
    "query": "label_values(gateway_requests_seconds_count,routeId)"
   }
  ]
 },
 "panels": [
  { "title": "Total Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests Served",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gateway_requests_seconds_count{job=~\"$gatewayService\"})"
    }
   ]
  },
  {
   "title": "Total Successful Requests Served",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", job=~\"$gatewayService\"})"
    }
   ]
  },
  {
   "title": "Total Unsuccessful Requests Served",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\", job=~\"$gatewayService\"})"
    }
   ]
  },
  { "title": "Request Processing Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "$routeId",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "repeat": "routeId",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "gateway_requests_seconds_sum{routeId=~\"$routeId\", job=~\"$gatewayService\"}/gateway_requests_seconds_count{routeId=~\"$routeId\", job=~\"$gatewayService\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Successful API Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "$routeId Success API Gateway Calls",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "repeat": "routeId",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", routeId=~\"$routeId\", job=~\"$gatewayService\"}",
       "legendFormat": "{{ job }} / {{ routeUri }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Unsuccessful API Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "$routeId Unsuccessful GW Calls",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "repeat": "routeId",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\", routeId=~\"$routeId\", job=~\"$gatewayService\"}",
       "legendFormat": "{{ job }} / {{ routeUri }}"
      }
     ]
    }
   ]
  },
  { "title": "API / HTTP Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "$routeId",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "repeat": "routeId",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gateway_requests_seconds_count{routeId=~\"$routeId\", job=~\"$gatewayService\"}) by (job, status)",
     "legendFormat": "{{ job }} / {{ status }}"
    }
   ]
  }
 ]
}