{
 "title": "System: Disk Performance",
 "tags": [ "System" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_disk_reads_completed_total, instance)"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "label_values(node_disk_reads_completed_total{instance=~\"$host(:[0-9]+)?\", device!~\"dm-.+\"}, device)"
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Latency",
   "type": "graph",
   "description": "Shows average latency for Reads and Writes IO Devices. Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems. Higher than normal latency also can indicate internal storage problems.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(rate(node_disk_read_time_seconds_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval]) / rate(node_disk_reads_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval])) or (irate(node_disk_read_time_seconds_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m]) / irate(node_disk_reads_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m]))",
     "legendFormat": "Read: {{ device }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "(rate(node_disk_write_time_seconds_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval]) / rate(node_disk_writes_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval])) or (irate(node_disk_write_time_seconds_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m]) / irate(node_disk_writes_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m]))",
     "legendFormat": "Write: {{ device }}"
    }
   ]
  },
  {
   "title": "Disk Operations",
   "type": "graph",
   "description": "Shows amount of physical IOs (reads and writes) different devices are serving. Spikes in number of IOs served often corresponds to performance problems due to IO subsystem overload.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_reads_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval]) or irate(node_disk_reads_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m])",
     "legendFormat": "Read: {{ device }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_writes_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval]) or irate(node_disk_writes_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m])",
     "legendFormat": "Write: {{ device }}"
    }
   ]
  },
  {
   "title": "Disk Bandwidth",
   "type": "graph",
   "description": "Shows volume of reads and writes the storage is handling. This can be better measure of IO capacity usage for network attached and SSD storage as it is often bandwidth limited. Amount of data being written to the disk can be used to estimate Flash storage life time.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_read_bytes_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval]) or irate(node_disk_read_bytes_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m])",
     "legendFormat": "Read: {{ device }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_written_bytes_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval]) or irate(node_disk_written_bytes_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m])",
     "legendFormat": "Write: {{ device }}"
    }
   ]
  },
  {
   "title": "Disk Load",
   "type": "graph",
   "description": "Disk Load shows how much disk was loaded for reads or writes as average number of outstanding requests at different period of time. High disk load is a good measure of actual storage utilization. Different storage types handle load differently - some will show latency increases on low loads others can handle higher load with no problems.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_read_time_seconds_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval])/1000 or irate(node_disk_read_time_seconds_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m])/1000",
     "legendFormat": "Read: {{ device }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_write_time_seconds_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval])/1000 or irate(node_disk_write_time_seconds_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m])/1000",
     "legendFormat": "Write: {{ device }}"
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "graph",
   "description": "Shows disk Utilization as percent of the time when there was at least one IO request in flight. It is designed to match utilization available in iostat tool. It is not very good measure of true IO Capacity Utilization. Consider looking at IO latency and Disk Load Graphs instead.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_io_time_seconds_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval])/1000 or irate(node_disk_io_time_seconds_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m])/1000",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Disk Operations Merge Ratio",
   "type": "graph",
   "description": "Shows how effectively Operating System is able to merge logical IO requests into physical requests. This is a good measure of the IO locality which can be used for workload characterization.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(1 + rate(node_disk_reads_merged_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval]) / rate(node_disk_reads_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval])) or (1 + irate(node_disk_reads_merged_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m]) / irate(node_disk_reads_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m]))",
     "legendFormat": "Read Ratio: {{ device }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "(1 + rate(node_disk_writes_merged_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval]) / rate(node_disk_writes_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[$interval])) or (1 + irate(node_disk_writes_merged_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m]) / irate(node_disk_writes_completed_total{device=~\"$device\", instance=~\"$host(:[0-9]+)?\"}[5m]))",
     "legendFormat": "Write Ratio: {{ device }}"
    }
   ]
  },
  {
   "title": "Disk IO Size",
   "type": "graph",
   "description": "Shows average size of a single disk operation.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$host(:[0-9]+)?\", device=~\"$device\"}[$interval]) / 512 / rate(node_disk_reads_completed_total{instance=~\"$host(:[0-9]+)?\", device=~\"$device\"}[$interval]) or irate(node_disk_read_bytes_total{instance=~\"$host(:[0-9]+)?\", device=~\"$device\"}[5m]) / 512 / irate(node_disk_reads_completed_total{instance=~\"$host(:[0-9]+)?\", device=~\"$device\"}[5m]) ",
     "legendFormat": "Read size: {{ device }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$host(:[0-9]+)?\", device=~\"$device\"}[$interval]) / 512 / rate(node_disk_writes_completed_total{instance=~\"$host(:[0-9]+)?\", device=~\"$device\"}[$interval]) or irate(node_disk_written_bytes_total{instance=~\"$host(:[0-9]+)?\", device=~\"$device\"}[5m]) / 512 / irate(node_disk_writes_completed_total{instance=~\"$host(:[0-9]+)?\", device=~\"$device\"}[5m]) ",
     "legendFormat": "Write size: {{ device }}"
    }
   ]
  }
 ]
}
{
 "title": "System: Disk Space",
 "tags": [ "System" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_filesystem_avail_bytes, instance)"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "label_values(node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}, mountpoint)"
   }
  ]
 },
 "panels": [
  {
   "title": "Mountpoint $mountpoint",
   "type": "graph",
   "description": "Amount of disk space used and available on various mount points.  Running out of disk space on OS volume,  database volume or volume used for temporary space can cause downtime.   Some storage may also have reduced performance when small amount of space is available.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "repeat": "mountpoint",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_size_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"} - node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Used (device {{ device }}, {{ fstype }})"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\",  fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Free (device {{ device }}, {{ fstype }})"
    }
   ]
  },
  {
   "title": "Mountpoint $mountpoint",
   "type": "graph",
   "description": "Amount of disk space used and available on various mount points.  Running out of disk space on OS volume,  database volume or volume used for temporary space can cause downtime.   Some storage may also have reduced performance when small amount of space is available.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_size_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"} - node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Used (device {{ device }}, {{ fstype }})"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\",  fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Free (device {{ device }}, {{ fstype }})"
    }
   ]
  },
  {
   "title": "Mountpoint $mountpoint",
   "type": "graph",
   "description": "Amount of disk space used and available on various mount points.  Running out of disk space on OS volume,  database volume or volume used for temporary space can cause downtime.   Some storage may also have reduced performance when small amount of space is available.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_size_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"} - node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Used (device {{ device }}, {{ fstype }})"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\",  fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Free (device {{ device }}, {{ fstype }})"
    }
   ]
  },
  {
   "title": "Mountpoint $mountpoint",
   "type": "graph",
   "description": "Amount of disk space used and available on various mount points.  Running out of disk space on OS volume,  database volume or volume used for temporary space can cause downtime.   Some storage may also have reduced performance when small amount of space is available.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_size_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"} - node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Used (device {{ device }}, {{ fstype }})"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\",  fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Free (device {{ device }}, {{ fstype }})"
    }
   ]
  },
  {
   "title": "Mountpoint $mountpoint",
   "type": "graph",
   "description": "Amount of disk space used and available on various mount points.  Running out of disk space on OS volume,  database volume or volume used for temporary space can cause downtime.   Some storage may also have reduced performance when small amount of space is available.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_size_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"} - node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Used (device {{ device }}, {{ fstype }})"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\",  fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Free (device {{ device }}, {{ fstype }})"
    }
   ]
  },
  {
   "title": "Mountpoint $mountpoint",
   "type": "graph",
   "description": "Amount of disk space used and available on various mount points.  Running out of disk space on OS volume,  database volume or volume used for temporary space can cause downtime.   Some storage may also have reduced performance when small amount of space is available.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_size_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"} - node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Used (device {{ device }}, {{ fstype }})"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\",  fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Free (device {{ device }}, {{ fstype }})"
    }
   ]
  },
  {
   "title": "Mountpoint $mountpoint",
   "type": "graph",
   "description": "Amount of disk space used and available on various mount points.  Running out of disk space on OS volume,  database volume or volume used for temporary space can cause downtime.   Some storage may also have reduced performance when small amount of space is available.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_size_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"} - node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Used (device {{ device }}, {{ fstype }})"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_avail_bytes{instance=~\"$host(:[0-9]+)?\",  fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\", mountpoint=\"$mountpoint\"}",
     "legendFormat": "Free (device {{ device }}, {{ fstype }})"
    }
   ]
  }
 ]
}
{
 "title": "System: Overview",
 "tags": [ "System" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_load1, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "node_time_seconds{instance=~\"$host(:[0-9]+)?\"} - node_boot_time_seconds{instance=~\"$host(:[0-9]+)?\"}"
    }
   ]
  },
  {
   "title": "Virtual CPUs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"user\", instance=~\"$host(:[0-9]+)?\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host(:[0-9]+)?\"}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(node_memory_MemAvailable_bytes{instance=~\"$host(:[0-9]+)?\"} or (node_memory_MemFree_bytes{instance=~\"$host(:[0-9]+)?\"} + node_memory_Buffers_bytes{instance=~\"$host(:[0-9]+)?\"} + node_memory_Cached_bytes{instance=~\"$host(:[0-9]+)?\"})) / node_memory_MemTotal_bytes{instance=~\"$host(:[0-9]+)?\"} * 100"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "node_load1{instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Load 1m"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Total"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host(:[0-9]+)?\"} - (node_memory_MemAvailable_bytes{instance=~\"$host(:[0-9]+)?\"} or (node_memory_MemFree_bytes{instance=~\"$host(:[0-9]+)?\"} + node_memory_Buffers_bytes{instance=~\"$host(:[0-9]+)?\"} + node_memory_Cached_bytes{instance=~\"$host(:[0-9]+)?\"}))",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$host(:[0-9]+)?\"} or (node_memory_MemFree_bytes{instance=~\"$host(:[0-9]+)?\"} + node_memory_Buffers_bytes{instance=~\"$host(:[0-9]+)?\"} + node_memory_Cached_bytes{instance=~\"$host(:[0-9]+)?\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"$host(:[0-9]+)?\"}[$interval])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\", instance=~\"$host(:[0-9]+)?\"})) or sum(irate(node_cpu_seconds_total{instance=~\"$host(:[0-9]+)?\"}[5m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\", instance=~\"$host(:[0-9]+)?\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory Distribution",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host(:[0-9]+)?\"} - (node_memory_MemFree_bytes{instance=~\"$host(:[0-9]+)?\"} + node_memory_Buffers_bytes{instance=~\"$host(:[0-9]+)?\"} + node_memory_Cached_bytes{instance=~\"$host(:[0-9]+)?\"})",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemFree_bytes{instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Free"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Buffers_bytes{instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Buffers"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Cached_bytes{instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_forks_total{instance=~\"$host(:[0-9]+)?\"}[$interval]) or irate(node_forks_total{instance=~\"$host(:[0-9]+)?\"}[5m])",
     "legendFormat": "Forks"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_running{instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Processes in runnable state"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_blocked{instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Processes blocked waiting for I/O to complete"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_context_switches_total{instance=~\"$host(:[0-9]+)?\"}[$interval]) or irate(node_context_switches_total{instance=~\"$host(:[0-9]+)?\"}[5m])",
     "legendFormat": "Context Switches"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_intr_total{instance=~\"$host(:[0-9]+)?\"}[$interval]) or irate(node_intr_total{instance=~\"$host(:[0-9]+)?\"}[5m])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$host(:[0-9]+)?\", device!=\"lo\"}[$interval]) or irate(node_network_receive_bytes_total{instance=~\"$host(:[0-9]+)?\", device!=\"lo\"}[5m])",
     "legendFormat": "Inbound: {{ device }}"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$host(:[0-9]+)?\", device!=\"lo\"}[$interval]) or irate(node_network_transmit_bytes_total{instance=~\"$host(:[0-9]+)?\", device!=\"lo\"}[5m])",
     "legendFormat": "Outbound: {{ device }}"
    }
   ]
  },
  {
   "title": "Network Utilization Hourly",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$host(:[0-9]+)?\", device!=\"lo\"}[1h]))",
     "legendFormat": "Received"
    },
    {
     "calculatedInterval": "2s",
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$host(:[0-9]+)?\", device!=\"lo\"}[1h]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$host(:[0-9]+)?\"} - node_memory_SwapFree_bytes{instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_SwapFree_bytes{instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pswpin{instance=~\"$host(:[0-9]+)?\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{instance=~\"$host(:[0-9]+)?\"}[5m]) * 4096",
     "legendFormat": "Swap In"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pswpout{instance=~\"$host(:[0-9]+)?\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{instance=~\"$host(:[0-9]+)?\"}[5m]) * 4096",
     "legendFormat": "Swap Out"
    }
   ]
  },
  {
   "title": "I/O Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgin{instance=~\"$host(:[0-9]+)?\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=~\"$host(:[0-9]+)?\"}[5m]) * 1024",
     "legendFormat": "Page In"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgout{instance=~\"$host(:[0-9]+)?\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=~\"$host(:[0-9]+)?\"}[5m]) * 1024",
     "legendFormat": "Page Out"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_filefd_maximum{instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Limit"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_filefd_allocated{instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Allocated"
    }
   ]
  }
 ]
}